# Generated by Django 5.0.3 on 2024-12-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='events',
            field=models.JSONField(default=list),
        ),
    ]
