# Generated by Django 5.0.3 on 2024-12-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_recipe_events_event'),
    ]

    operations = [
    ]
