# Generated by Django 5.1.4 on 2024-12-14 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_add_initial_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('items', models.JSONField(default=list)),
            ],
        ),
    ]
